webapp/WEB-INF/conf/plugins/forms_context.xml
This transaction manager allows plugins to use multi plugin transactions, and nested transactions.
=> FORMS-362 : [BO] - Rollback NOK on genatt_response table

src/java/fr/paris/lutece/plugins/forms/util/FormsConstants.java, src/java/fr/paris/lutece/plugins/forms/web/CompositeQuestionDisplay.java, src/java/fr/paris/lutece/plugins/forms/web/FormResponseManager.java, src/java/fr/paris/lutece/plugins/forms/web/FormXPage.java, webapp/WEB-INF/templates/skin/plugins/forms/composite_template/view_question.html
FORMS-247 : Conditionnal options on a previous step field is not working
=> FORMS-247 : Conditionnal options on a previous step field is not working

src/java/fr/paris/lutece/plugins/forms/resources/forms_messages.properties, src/java/fr/paris/lutece/plugins/forms/resources/forms_messages_fr.properties, src/java/fr/paris/lutece/plugins/forms/web/FormXPage.java
this should help the user and stat tools like matomo
=> FORMS-459: Add the current step in the page title

pom.xml, src/java/fr/paris/lutece/plugins/forms/web/CompositeQuestionDisplay.java, webapp/WEB-INF/plugins/forms.xml
I picked the modifications made to CompositeQuestionDisplay in branch develop to prevent problems when we will merge this branch into develop
=> FORMS-476 : Correctly show comment in BO response detail

webapp/WEB-INF/templates/admin/plugins/forms/forms_commons.html
=> LUT-25112 : [BO] Help text for the configuration of the dates of

src/java/fr/paris/lutece/plugins/forms/business/MultiviewConfig.java, src/java/fr/paris/lutece/plugins/forms/export/pdf/AbstractPdfFileGenerator.java, src/java/fr/paris/lutece/plugins/forms/export/pdf/PdfFileGenerator.java, src/java/fr/paris/lutece/plugins/forms/export/pdffull/PdfFullFileGenerator.java, src/java/fr/paris/lutece/plugins/forms/resources/forms_messages.properties, src/java/fr/paris/lutece/plugins/forms/resources/forms_messages_fr.properties, src/java/fr/paris/lutece/plugins/forms/util/FormsConstants.java, src/java/fr/paris/lutece/plugins/forms/web/admin/MultiviewFormsJspBean.java, webapp/WEB-INF/templates/admin/plugins/forms/multiview/forms_multiview_config.html
Duplicate from PR 246 : https://github.com/lutece-platform/lutece-form-plugin-forms/pull/246
=> LUT-25445 : Export pdf view of responses from a pdf - load an html template

src/java/fr/paris/lutece/plugins/forms/resources/forms_messages.properties, src/java/fr/paris/lutece/plugins/forms/resources/forms_messages_fr.properties, src/java/fr/paris/lutece/plugins/forms/service/MultiviewFormService.java, src/java/fr/paris/lutece/plugins/forms/web/admin/FormMultiviewConfigJspBean.java, webapp/WEB-INF/templates/admin/plugins/forms/manage_multiview_config.html
SQL script to fix existing question (type image and files ) as non displayable in response view : 
update forms_question fq
inner join genatt_entry ge ON ge.id_entry  = fq.id_entry
inner join genatt_entry_type get2 on get2.id_type = ge.id_type
set fq.is_visible_multiview_global = 0, fq.is_visible_multiview_form_selected  = 0
where get2.class_name = 'forms.entryTypeFile' or get2.class_name = 'forms.entryTypeImage'
or get2.class_name = 'forms.entryTypeAutomaticFileReading' or get2.class_name = 'forms.entryTypeGalleryImage';
=> LUT-26108 : Error if image or file selected in Vue of responses

webapp/WEB-INF/templates/admin/plugins/forms/entries/all_entry_commons.html
list is not populated when expected
=> LUT-25083 : [BO] ManageQuestions.jsp - Page not found if a reference list is not populated when expected

webapp/WEB-INF/templates/skin/plugins/forms/entries/fill_entry_type_camera.html
https://dev.lutece.paris.fr/bugtracker/issues/26370
=> LUT-26370 : Camera field : error message is empty

src/java/fr/paris/lutece/plugins/forms/web/breadcrumb/VerticalBreadcrumb.java
https://dev.lutece.paris.fr/bugtracker/issues/26581
=> LUT-26581 : Fix IndexOutOfBoundsException when selecting the vertical breadcrumb type

webapp/WEB-INF/templates/skin/plugins/forms/entries/fill_entry_type_number.html, webapp/WEB-INF/templates/skin/plugins/forms/entries/fill_entry_type_text.html, webapp/WEB-INF/templates/skin/plugins/forms/entries/fill_entry_type_text_area.html
Error 500 when a form contains text field, text area field, number field
=> lut-26683: Error 500 when a form contains text field, text area field, number field

webapp/WEB-INF/templates/skin/plugins/forms/entries/fill_entry_type_geolocation.html, webapp/WEB-INF/templates/skin/plugins/forms/entries/readonly_entry_type_geolocation.html
https://dev.lutece.paris.fr/bugtracker/issues/25286
There are also PR on lutece-genattrs-module-genericattributes-openstreetmap and on lutece-genattrs-plugin-genericattributes linked with this ticket
=> LUT-25286 : fix geolocation field overwriting when iteration

src/java/fr/paris/lutece/plugins/forms/export/csv/FormResponseCsvExport.java
https://dev.lutece.paris.fr/bugtracker/issues/26411
=> LUT-26411: CSV export following question export order

src/java/fr/paris/lutece/plugins/forms/web/FormXPage.java
PR : https://dev.lutece.paris.fr/bugtracker/issues/26660
=> LUT-26660: Fix session error when refreshing a form

webapp/WEB-INF/templates/admin/plugins/forms/entries/modify_entry_type_select.html
https://dev.lutece.paris.fr/bugtracker/issues/26354
=> LUT-26354: withdraw option "no display title"

src/java/fr/paris/lutece/plugins/forms/web/admin/FormExportJspBean.java
https://dev.lutece.paris.fr/bugtracker/issues/26000
=> LUT-26000: simplify export order algorithm

webapp/WEB-INF/templates/admin/plugins/forms/validators/date_value_template.html
date conditional control format
=> date conditional control format

webapp/WEB-INF/templates/admin/plugins/forms/entries/fill_entry_type_number.html, webapp/WEB-INF/templates/admin/plugins/forms/entries/fill_entry_type_text.html, webapp/WEB-INF/templates/admin/plugins/forms/entries/fill_entry_type_text_area.html, webapp/WEB-INF/templates/admin/plugins/forms/entries/modify_entry_type_number.html, webapp/WEB-INF/templates/admin/plugins/forms/entries/modify_entry_type_text.html, webapp/WEB-INF/templates/admin/plugins/forms/entries/modify_entry_type_text_area.html, webapp/WEB-INF/templates/skin/plugins/forms/entries/fill_entry_type_number.html
initializes field_autocomplete to an empty map, to prevents a NullPointerException when trying to access or to config form that contain input-text, input-text-area, unput-number
=> LUT-26683: initializes field_autocomplete to an empty map

webapp/WEB-INF/templates/admin/plugins/forms/composite/view_step_bo.html
https://dev.lutece.paris.fr/bugtracker/issues/26988
=> LUT-26988: [BO] Adding a missing request parameter

webapp/WEB-INF/templates/skin/plugins/forms/entries/fill_entry_type_gallery_image.html
Image gallery is now placed after text description, which is transformed from span to paragraph
=> LUT-26984 : Accessibility - Enhancement for screen reader on entry type Gallery Image

src/java/fr/paris/lutece/plugins/forms/resources/forms_messages.properties, src/java/fr/paris/lutece/plugins/forms/resources/forms_messages_fr.properties, src/java/fr/paris/lutece/plugins/forms/service/provider/GenericFormsProvider.java
new default template, new bookmark form title
=> lut-26727: new default template, new bookmark form title

webapp/WEB-INF/templates/admin/plugins/forms/composite/view_question.html
LUT-26989:  javascript is not loaded for conditionnal questions
=> LUT-26989:  javascript is not loaded for conditionnal questions

src/java/fr/paris/lutece/plugins/forms/export/AbstractFileGenerator.java
https://dev.lutece.paris.fr/bugtracker/issues/26933
fix filename without "/"
=> LUT-26933 : fix Export pdf error

src/java/fr/paris/lutece/plugins/forms/resources/forms_messages.properties, src/java/fr/paris/lutece/plugins/forms/resources/forms_messages_fr.properties, src/java/fr/paris/lutece/plugins/forms/web/admin/FormResponseJspBean.java, webapp/WEB-INF/templates/admin/plugins/forms/composite/view_group_edition.html, webapp/WEB-INF/templates/admin/plugins/forms/composite/view_step_read_only.html
This PR concerns the same subject as this previous PR: https://github.com/lutece-platform/lutece-form-plugin-forms/pull/313, however it comes from a new fork to fix the many conflicts it had
=> LUT-27192 : add action and btn to add and remove iteration on BO forms

src/java/fr/paris/lutece/plugins/forms/resources/forms_messages.properties, src/java/fr/paris/lutece/plugins/forms/resources/forms_messages_fr.properties, src/java/fr/paris/lutece/plugins/forms/service/entrytype/EntryTypeSlot.java, src/sql/plugins/genericattributes/upgrade/upgrade_db_genericattributes_for_slot.sql, webapp/WEB-INF/conf/plugins/forms_context.xml, webapp/WEB-INF/templates/admin/plugins/forms/entries/create_entry_type_slot.html, webapp/WEB-INF/templates/admin/plugins/forms/entries/fill_entry_type_slot.html, webapp/WEB-INF/templates/admin/plugins/forms/entries/modify_entry_type_slot.html, webapp/WEB-INF/templates/admin/plugins/forms/entries/readonly_entry_type_slot.html, webapp/WEB-INF/templates/skin/plugins/forms/entries/fill_entry_type_slot.html, webapp/WEB-INF/templates/skin/plugins/forms/entries/readonly_entry_type_slot.html
add elements to create slot entries
=> LUT-27422 : add elements to create slot entries

webapp/css/admin/plugins/forms/forms.css
https://dev.lutece.paris.fr/bugtracker/issues/27330
=> LUT-27330: fix scrolling on the question manager

webapp/WEB-INF/templates/admin/plugins/forms/create_transition.html
https://dev.lutece.paris.fr/bugtracker/issues/27619
=> LUT-27619: Remove a cancel button witch cause nested windows

src/java/fr/paris/lutece/plugins/forms/web/admin/FormControlJspBean.java
https://dev.lutece.paris.fr/bugtracker/issues/27711
=> LUT-27711: Fix a bad redirection after deleting a transition control

src/java/fr/paris/lutece/plugins/forms/service/provider/GenericFormsProvider.java, webapp/WEB-INF/conf/plugins/forms.properties
https://dev.lutece.paris.fr/bugtracker/issues/26829
With this PR, you need to use a version of workflow core with this PR included 
https://github.com/lutece-platform/lutece-wf-library-workflow-core/pull/26
=> LUT-26829 Bookmark content is not added to exports

src/java/fr/paris/lutece/plugins/forms/service/provider/GenericFormsProvider.java
https://dev.lutece.paris.fr/bugtracker/issues/27866
=> LUT-27866 : fix regression link to 26829 (Object Value in InfoMarker)

src/java/fr/paris/lutece/plugins/forms/resources/forms_messages.properties, src/java/fr/paris/lutece/plugins/forms/resources/forms_messages_fr.properties, src/java/fr/paris/lutece/plugins/forms/validation/AbstractNumberValidator.java, src/java/fr/paris/lutece/plugins/forms/validation/NumberInferiorValidator.java, src/java/fr/paris/lutece/plugins/forms/validation/NumberSuperiorValidator.java, webapp/WEB-INF/conf/plugins/forms_context.xml, webapp/WEB-INF/templates/admin/plugins/forms/validators/number_value_template.html
https://dev.lutece.paris.fr/bugtracker/issues/25289
=> LUT-25289: add control for superior and inferior number

src/java/fr/paris/lutece/plugins/forms/business/FormQuestionResponseDAO.java, src/java/fr/paris/lutece/plugins/forms/business/FormQuestionResponseHome.java, src/java/fr/paris/lutece/plugins/forms/business/IFormQuestionResponseDAO.java, src/java/fr/paris/lutece/plugins/forms/export/csv/CSVDataLine.java, src/java/fr/paris/lutece/plugins/forms/export/csv/CSVFileGenerator.java, src/java/fr/paris/lutece/plugins/forms/export/csv/CSVHeader.java, src/java/fr/paris/lutece/plugins/forms/export/csv/CSVUtil.java, src/java/fr/paris/lutece/plugins/forms/export/csv/FormResponseCsvExport.java
https://dev.lutece.paris.fr/bugtracker/issues/28145
=> LUT-28145 : Fix csv header

src/java/fr/paris/lutece/plugins/forms/export/pdf/AbstractPdfFileGenerator.java
https://dev.lutece.paris.fr/bugtracker/issues/28146
=> LUT-28146 : PDF export - iteration

webapp/WEB-INF/templates/admin/plugins/forms/composite/view_group_edition.html
https://dev.lutece.paris.fr/bugtracker/issues/28135
=> LUT-28135 : Group - question in huge size

webapp/WEB-INF/templates/admin/plugins/forms/multiview/includes/include_manage_multiview_forms_header.html
https://dev.lutece.paris.fr/bugtracker/issues/27965
=> LUT-27965: Fix issue in a hover label

src/java/fr/paris/lutece/plugins/forms/business/QuestionHome.java, src/java/fr/paris/lutece/plugins/forms/export/csv/CSVFileGenerator.java, src/java/fr/paris/lutece/plugins/forms/export/csv/CSVHeader.java, src/java/fr/paris/lutece/plugins/forms/resources/forms_messages.properties, src/java/fr/paris/lutece/plugins/forms/resources/forms_messages_fr.properties, src/java/fr/paris/lutece/plugins/forms/web/admin/FormExportJspBean.java, src/java/fr/paris/lutece/plugins/forms/web/admin/FormWorkflowConfigJspBean.java, webapp/WEB-INF/templates/admin/plugins/forms/manage_export.html, webapp/WEB-INF/templates/admin/plugins/forms/manage_workflow_config.html
Must be merge after https://github.com/lutece-platform/lutece-form-plugin-forms/pull/356
=>  LUT-28390: Change question display order in manage_workflow_config

src/java/fr/paris/lutece/plugins/forms/resources/forms_messages_fr.properties
https://dev.lutece.paris.fr/bugtracker/issues/26415?issue_count=99&issue_position=17&next_issue_id=26414&prev_issue_id=27844
=> LUT-26415: Fix of a sentence in the form creation

webapp/WEB-INF/templates/admin/plugins/forms/modify_publication.html
https://dev.lutece.paris.fr/bugtracker/issues/28431
=> LUT-28431: Fix of the background color of the publication date form when we are in dark mode

src/java/fr/paris/lutece/plugins/forms/web/admin/FormMultiviewConfigJspBean.java, webapp/WEB-INF/templates/admin/plugins/forms/manage_multiview_config.html
Must be merge after https://github.com/lutece-platform/lutece-form-plugin-forms/pull/356
=> LUT-28392: Response view - add a Button to set the question display order

src/java/fr/paris/lutece/plugins/forms/web/admin/FormJspBean.java, webapp/WEB-INF/templates/admin/plugins/forms/manage_forms_questions_publication.html
Must be merge after https://github.com/lutece-platform/lutece-form-plugin-forms/pull/356
=> LUT-28388: Change question display order in publication

src/java/fr/paris/lutece/plugins/forms/web/admin/FormMultiviewConfigJspBean.java, webapp/WEB-INF/templates/admin/plugins/forms/manage_multiview_config.html
Must be merge after https://github.com/lutece-platform/lutece-form-plugin-forms/pull/356
=> LUT-28389: Change question display order in manage_multiview_config

src/java/fr/paris/lutece/plugins/forms/resources/forms_messages.properties, src/java/fr/paris/lutece/plugins/forms/resources/forms_messages_fr.properties, src/java/fr/paris/lutece/plugins/forms/validation/AbstractDayDistanceValidator.java, src/java/fr/paris/lutece/plugins/forms/validation/DayDelayMinimumValidator.java, webapp/WEB-INF/conf/plugins/forms_context.xml, webapp/WEB-INF/templates/admin/plugins/forms/validators/day_distance_value_template.html
Number of minimum elapsed days 
https://dev.lutece.paris.fr/bugtracker/issues/26977
=> LUT-26977: Add a validator for date field

src/java/fr/paris/lutece/plugins/forms/resources/forms_messages.properties, src/java/fr/paris/lutece/plugins/forms/resources/forms_messages_fr.properties, src/sql/plugins/genericattributes/upgrade/update_db_genericattributes-2.4.5-2.4.6.sql, webapp/WEB-INF/templates/admin/plugins/forms/entries/create_entry_type_select_order.html, webapp/WEB-INF/templates/admin/plugins/forms/entries/fill_entry_type_select_order.html, webapp/WEB-INF/templates/admin/plugins/forms/entries/modify_entry_type_select_order.html, webapp/WEB-INF/templates/skin/plugins/forms/entries/fill_entry_type_select_order.html
The features added in this pull request are dependent on the following PR made for the `lutece-genattrs-plugin-genericattributes`:
- https://github.com/lutece-platform/lutece-genattrs-plugin-genericattributes/pull/76
=> LUT-25400: Updated the sortable list to introduce new features allowing the selection/sorting of items between two lists

src/test/java/fr/paris/lutece/plugins/forms/util/FormsEntryUtilsTest.java
added tests for FormEntryUtils
=> FORMS-825 : FormsEntryUtils coverage

webapp/WEB-INF/templates/admin/plugins/forms/entries/fill_entry_type_file.html
The fill_entry_type_file does not appear in the BO editing form
=> LUT-28567: Edit a file in BO

src/java/fr/paris/lutece/plugins/forms/resources/forms_messages.properties, src/java/fr/paris/lutece/plugins/forms/resources/forms_messages_fr.properties, src/java/fr/paris/lutece/plugins/forms/service/provider/GenericFormsProvider.java, src/java/fr/paris/lutece/plugins/forms/web/FormResponseXPage.java, webapp/WEB-INF/templates/skin/plugins/forms/view_form_file.html
New marker for BO files that lists the download URLs of files specific to an input file, along with a marker that allows a user to access an authenticated view to retrieve the files
=> LUT-28678 : Files transmitted by the BO user to an FO user

src/java/fr/paris/lutece/plugins/forms/validation/AbstractListQuestionValidator.java, src/java/fr/paris/lutece/plugins/forms/validation/ListExactResponseValidator.java, src/java/fr/paris/lutece/plugins/forms/validation/ListMinResponseValidator.java
Pass the user's context locale as an argument
=> LUT-28725 : Pass the user's context locale as an argument.

src/java/fr/paris/lutece/plugins/forms/export/pdffull/PdfFullFileGenerator.java
Change in the file renaming policy to ensure no two files have the same name
=> LUT-29298: Change in the file renaming policy to ensure no two files have the same name
